disabled_rules:
 - trailing_whitespace
 - identifier_name
 - class_delegate_protocol
 - weak_delegate
 - line_length
 - cyclomatic_complexity
 - large_tuple
 - private_over_fileprivate
 - no_fallthrough_only
 - empty_enum_arguments
 - force_try
excluded:
  - Pods
  - fastane
  - installer
  - vendor/
  - Modules/EssUI/Sources/Third-Party
  - Modules/EssUI/Sources/TableAdapterCore/TableAdapter.swift
  - Modules/EssUI/Sources/TableAdapterCore/TableAdapterHelper.swift
  - Essentia/Core/ComponentsTableAdapter/TableAdapter.swift
  - Essentia/Core/ComponentsTableAdapter/TableAdapterHelper.swift
