disabled_rules:
 - trailing_whitespace
 - identifier_name
 - class_delegate_protocol
 - weak_delegate
 - line_length
 - cyclomatic_complexity
excluded:
  - Pods
  - fastane
  - installer
  - vendor/
  - Essentia/Third-Party
  - Essentia/Core/ComponentsTableAdapter/TableAdapter.swift
  - Essentia/Core/ComponentsTableAdapter/TableAdapterHelper.swift
