
default_platform(:ios)

platform :ios do

  before_all do
    create_keychain(
        name: ENV["MATCH_KEYCHAIN_NAME"],
	password: ENV["MATCH_PASSWORD"],
	default_keychain: true,
	unlock: true,
	timeout: 3600,
	add_to_search_list: true,
	verbose: true
    )
    #dev_mobile
    #ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["IOS_DEV_TEAM"] = "https://hooks.slack.com/services/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"
  end

  desc "installing current pod dependecies"
  lane :pod_install do
    cocoapods(
      clean: true,
      repo_update: true,
      use_bundle_exec: false
    )
  end



  desc "Push a new beta build to TestFlight"
  lane :beta do
    generateProfiles(type: "Adhoc", identifier: "impl.essentia.Essentia")
    ensure_git_branch(branch: "feature/fastlane-CD")

    #Increment build
    ensure_git_status_clean
    increment_build_number(xcodeproj: "Essentia.xcodeproj")
    commit_version_bump(xcodeproj: "Essentia.xcodeproj")
    add_git_tag
    push_to_git_remote
    
    pod_install

    match(
      app_identifier: "impl.essentia.Essentia",
      type: "appstore",
      git_branch: "develop",
      readonly: true
    )

    # build app
    gym(
      scheme: "Essentia",
      export_method: "app-store",
      configuration: "Release",
      export_options: {
        uploadBitcode: false,
        compileBitcode: false,
        method: "app-store",
        provisioningProfiles: { 
         "impl.essentia.Essentia" => "match AppStore impl.essentia.Essentia",
        }
      } 
    )

    changelog_from_git_commits
    upload_to_testflight

    #Print version to slack
    release_version_number = get_build_number(xcodeproj: 'Essentia.xcodeproj')
    slack(message: "Build #{release_version_number} is ready for test on Testflight.")

  end

  lane :build do
    build_app(workspace: "Essentia.xcworkspace", scheme: "Essentia")
  end
  
  error do |lane, exception|
     slack(
      message: exception.message,
      channel: ENV["IOS_DEV_TEAM"]
    )
  end

    after_all do |lane|
        delete_keychain(
            name: ENV["MATCH_KEYCHAIN_NAME"]
        )
    end

end


